//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>test</summary>
	[PublishedModel("test")]
	public partial class Test : PublishedContentModel, IProject1
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "test";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Test, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Test(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetPageTitle(this, _publishedValueFallback);

		///<summary>
		/// Project Baner - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectBanerHeadline")]
		public virtual string ProjectBanerHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectBanerHeadline(this, _publishedValueFallback);

		///<summary>
		/// Project Banner - Link 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectBannerLink2")]
		public virtual string ProjectBannerLink2 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectBannerLink2(this, _publishedValueFallback);

		///<summary>
		/// Project Banner - Link Text 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectBannerLinkText2")]
		public virtual string ProjectBannerLinkText2 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectBannerLinkText2(this, _publishedValueFallback);

		///<summary>
		/// Project - Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDate")]
		public virtual string ProjectDate => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectDate(this, _publishedValueFallback);

		///<summary>
		/// Project - Image 0
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage0")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage0 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectImage0(this, _publishedValueFallback);

		///<summary>
		/// Project - Image 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage1 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectImage1(this, _publishedValueFallback);

		///<summary>
		/// Project - Image 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage2 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectImage2(this, _publishedValueFallback);

		///<summary>
		/// Project - Start Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectStartText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ProjectStartText => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectStartText(this, _publishedValueFallback);

		///<summary>
		/// Project - Text 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText1")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ProjectText1 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectText1(this, _publishedValueFallback);

		///<summary>
		/// Project - Text 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText2")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ProjectText2 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectText2(this, _publishedValueFallback);

		///<summary>
		/// Project - Text 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText3")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ProjectText3 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectText3(this, _publishedValueFallback);

		///<summary>
		/// Project - Text 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectText4")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ProjectText4 => global::Umbraco.Cms.Web.Common.PublishedModels.Project1.GetProjectText4(this, _publishedValueFallback);
	}
}
