//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Services Section</summary>
	[PublishedModel("servicesSection")]
	public partial class ServicesSection : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "servicesSection";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ServicesSection, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ServicesSection(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Service - Solution 1 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution1Headline")]
		public virtual string ServiceSolution1Headline => this.Value<string>(_publishedValueFallback, "serviceSolution1Headline");

		///<summary>
		/// Service - Solution 1 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution1Image");

		///<summary>
		/// Service - Solution 1 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution1Link")]
		public virtual string ServiceSolution1Link => this.Value<string>(_publishedValueFallback, "serviceSolution1Link");

		///<summary>
		/// Service - Solution 1 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution1Text")]
		public virtual string ServiceSolution1Text => this.Value<string>(_publishedValueFallback, "serviceSolution1Text");

		///<summary>
		/// Service - Solution 2 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution2Headline")]
		public virtual string ServiceSolution2Headline => this.Value<string>(_publishedValueFallback, "serviceSolution2Headline");

		///<summary>
		/// Service - Solution 2 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution2Image");

		///<summary>
		/// Service - Solution 2 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution2Link")]
		public virtual string ServiceSolution2Link => this.Value<string>(_publishedValueFallback, "serviceSolution2Link");

		///<summary>
		/// Service - Solution 2 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution2Text")]
		public virtual string ServiceSolution2Text => this.Value<string>(_publishedValueFallback, "serviceSolution2Text");

		///<summary>
		/// Service - Solution 3 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution3Headline")]
		public virtual string ServiceSolution3Headline => this.Value<string>(_publishedValueFallback, "serviceSolution3Headline");

		///<summary>
		/// Service - Solution 3 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution3Image");

		///<summary>
		/// Service - Solution 3 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution3Link")]
		public virtual string ServiceSolution3Link => this.Value<string>(_publishedValueFallback, "serviceSolution3Link");

		///<summary>
		/// Service - Solution 3 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution3Text")]
		public virtual string ServiceSolution3Text => this.Value<string>(_publishedValueFallback, "serviceSolution3Text");

		///<summary>
		/// Service - Solution 4 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution4Headline")]
		public virtual string ServiceSolution4Headline => this.Value<string>(_publishedValueFallback, "serviceSolution4Headline");

		///<summary>
		/// Service - Solution 4 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution4Image");

		///<summary>
		/// Service - Solution 4 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution4Link")]
		public virtual string ServiceSolution4Link => this.Value<string>(_publishedValueFallback, "serviceSolution4Link");

		///<summary>
		/// Service - Solution 4 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution4Text")]
		public virtual string ServiceSolution4Text => this.Value<string>(_publishedValueFallback, "serviceSolution4Text");

		///<summary>
		/// Service - Solution 5 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution5Headline")]
		public virtual string ServiceSolution5Headline => this.Value<string>(_publishedValueFallback, "serviceSolution5Headline");

		///<summary>
		/// Service - Solution 5 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution5Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution5Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution5Image");

		///<summary>
		/// Service - Solution 5 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution5Link")]
		public virtual string ServiceSolution5Link => this.Value<string>(_publishedValueFallback, "serviceSolution5Link");

		///<summary>
		/// Service - Solution 5 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution5Text")]
		public virtual string ServiceSolution5Text => this.Value<string>(_publishedValueFallback, "serviceSolution5Text");

		///<summary>
		/// Service - Solution 6 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution6Headline")]
		public virtual string ServiceSolution6Headline => this.Value<string>(_publishedValueFallback, "serviceSolution6Headline");

		///<summary>
		/// Service - Solution 6 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution6Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution6Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution6Image");

		///<summary>
		/// Service - Solution 6 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution6Link")]
		public virtual string ServiceSolution6Link => this.Value<string>(_publishedValueFallback, "serviceSolution6Link");

		///<summary>
		/// Service - Solution 6 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution6Text")]
		public virtual string ServiceSolution6Text => this.Value<string>(_publishedValueFallback, "serviceSolution6Text");

		///<summary>
		/// Service - Solution 7 - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution7Headline")]
		public virtual string ServiceSolution7Headline => this.Value<string>(_publishedValueFallback, "serviceSolution7Headline");

		///<summary>
		/// Service - Solution 7 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution7Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ServiceSolution7Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "serviceSolution7Image");

		///<summary>
		/// Service - Solution 7 - Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution7Link")]
		public virtual string ServiceSolution7Link => this.Value<string>(_publishedValueFallback, "serviceSolution7Link");

		///<summary>
		/// Service - Solution 7 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("serviceSolution7Text")]
		public virtual string ServiceSolution7Text => this.Value<string>(_publishedValueFallback, "serviceSolution7Text");
	}
}
